version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      # Checks out source code, i.e. grabs the public
      # source code and puts it into the docker image
      - checkout
      #  Restore Dotnet Packages
      - run: cd ./Solution/MitchRankChecker.RankCheckerTest && dotnet restore
      # Compile and build the application
      - run: cd ./Solution/MitchRankChecker.RankCheckerTest && dotnet build
      # Test the application
      - run: cd ./Solution/MitchRankChecker.RankCheckerTest && dotnet test --no-build
